"use client";

import { useMemo, useState } from "react";

export default function EventStatsSideBar({ teamStatuses = {}, playoffAlliances = [] }) {
  const [mode, setMode] = useState("rankings");
  const rankings = useMemo(() => Object.entries(teamStatuses || {}).map(([key, status]) => ({ key, rank: status?.qual?.ranking?.rank ?? Infinity, wins: status?.qual?.ranking?.record?.wins ?? 0, losses: status?.qual?.ranking?.record?.losses ?? 0, ties: status?.qual?.ranking?.record?.ties ?? 0 })).sort((a, b) => a.rank - b.rank), [teamStatuses]);

  return <div className="flex h-full flex-col bg-neutral-950"><div className="flex border-b border-white/10 p-2">{["rankings", ...(playoffAlliances.length ? ["alliances"] : [])].map((item) => <button key={item} onClick={() => setMode(item)} className={`flex-1 rounded-lg px-3 py-2 text-xs font-semibold capitalize ${mode === item ? "bg-white text-black" : "text-neutral-500 hover:bg-white/5 hover:text-white"}`}>{item}</button>)}</div><div className="min-h-0 flex-1 overflow-y-auto p-2">{mode === "rankings" ? <>{rankings.map((team) => <div key={team.key} className="mb-1 flex items-center gap-3 rounded-lg bg-white/[0.04] px-3 py-2"><span className="w-7 text-center font-mono text-xs font-bold">{Number.isFinite(team.rank) ? team.rank : "–"}</span><span className="flex-1 text-sm">#{team.key.replace("frc", "")}</span><span className="font-mono text-[10px] text-neutral-500">{team.wins}-{team.losses}{team.ties ? `-${team.ties}` : ""}</span></div>)}{!rankings.length && <Empty text="Rankings are not available yet." />}</> : <>{playoffAlliances.map((alliance, index) => <div key={alliance.name || index} className="mb-2 rounded-lg border border-white/10 bg-white/[0.04] p-3"><div className="flex justify-between text-xs font-semibold"><span>{alliance.name || `Alliance ${index + 1}`}</span><span className="text-neutral-500">{alliance.status?.record?.wins ?? 0}-{alliance.status?.record?.losses ?? 0}</span></div><div className="mt-2 flex gap-2">{(alliance.picks || []).map((team) => <span key={team} className="rounded bg-white/5 px-2 py-1 font-mono text-[10px]">#{team.replace("frc", "")}</span>)}</div></div>)}{!playoffAlliances.length && <Empty text="Alliance data is not available yet." />}</>}</div></div>;
}
function Empty({ text }) { return <div className="p-8 text-center text-xs text-neutral-600">{text}</div>; }
